### PR TITLE
[13.0][FIX] l10n_nl_tax_statement: case no match on tags

### LINKED ISSUE #318: [13.0] nl tax statement - Error since upgrade from 12 to 13
**Problem summary**
Since I had my database upgraded from Odoo12 CE to Odoo13 CE, the nl tax statement report (BTW aangifte rapport) leads to an error when I hit the "update" button in the report:
File "/var/lib/odoo/addons/13.0/l10n_nl_tax_statement/models/l10n_nl_vat_statement.py", line 408, in _get_tags_map     matching.update({tag.id: (res_code.group(0), "omzet")})
AttributeError: 'NoneType' object has no attribute 'group'

I am not sure if this is a program issue, a setup issue or a migration issue.

**Things I already tried unsuccesfully**
Updating the module
Uninstalling and reinstalling the module
Regenerate asset bundles
Checking the VAT setup and the Chart of Account setup (this is probably where my knowledge fails and maybe someone can give some pointers where to look)

**Full error log:**
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/var/lib/odoo/addons/13.0/l10n_nl_tax_statement/models/l10n_nl_vat_statement.py", line 430, in statement_update
    self._set_statement_lines(lines, move_lines)
  File "/var/lib/odoo/addons/13.0/l10n_nl_tax_statement/models/l10n_nl_vat_statement.py", line 457, in _set_statement_lines
    tags_map = self._get_tags_map()
  File "/var/lib/odoo/addons/13.0/l10n_nl_tax_statement/models/l10n_nl_vat_statement.py", line 408, in _get_tags_map
    matching.update({tag.id: (res_code.group(0), "omzet")})
AttributeError: 'NoneType' object has no attribute 'group'

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/l10n-netherlands/issues/318

@CasVissers-360ERP thanks for this fix!

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
Should also be applied to v14?

**Review by CasVissers-360ERP — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Code looking good. Test failure seems unrelated, but do these errors ring a bell?
```
ERROR: TestTaxInvoiceBasis.test_04_tax_no_nl
Traceback (most recent call last):
  File "/home/travis/build/OCA/l10n-netherlands/l10n_nl_tax_invoice_basis/tests/test_tax_invoice_basis.py", line 151, in test_04_tax_no_nl
    self.invoice.action_post()
  File "/home/travis/odoo-13.0/addons/account/models/account_move.py", line 2345, in action_post
    return self.post()
  File "/home/travis/odoo-13.0/addons/account/models/account_move.py", line 2241, in post
    raise UserError(_('The entry %s (id %s) is already posted.') % (move.name, move.id))
odoo.exceptions.UserError: ('The entry BILL/2017/0001 (id 20) is already posted.', '')
```

**Comment by astirpe** [comment]
Rebased

**Review by NL66278 — APPROVED** [review]
:+1: LGTM
